# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
envlist = lint, validate-kserve, validate-llm, validate-llm-cos
skipsdist = True

[vars]
kserve_path = {tox_root}/products/kserve
llm_path = {tox_root}/products/llm
llm_cos_path = {tox_root}/deployments/llm-cos

[testenv]
skip_install = True
allowlist_externals =
    terraform
    tflint

[testenv:fmt]
description = Apply Terraform formatting and tflint fixes
commands =
    terraform fmt -recursive {tox_root}
    tflint --recursive --fix --chdir={tox_root}

[testenv:lint]
description = Check Terraform formatting and lint with tflint
commands =
    terraform fmt -recursive -check -diff {tox_root}
    tflint --recursive --chdir={tox_root}

[testenv:validate-kserve]
description = Validate the kserve product root module
commands =
    terraform -chdir={[vars]kserve_path} init -backend=false
    terraform -chdir={[vars]kserve_path} validate

[testenv:validate-llm]
description = Validate the llm product root module
commands =
    terraform -chdir={[vars]llm_path} init -backend=false
    terraform -chdir={[vars]llm_path} validate

[testenv:validate-llm-cos]
description = Validate the llm-cos deployment root module
commands =
    terraform -chdir={[vars]llm_cos_path} init -backend=false
    terraform -chdir={[vars]llm_cos_path} validate
